edition = "2021"
style_edition = "2024"
imports_granularity = "One"
imports_layout = "Vertical"
fn_params_layout = "Vertical"
max_width = 90
struct_lit_single_line = false
use_small_heuristics = "Off"
