#!/usr/bin/env bash
#
# Build every distributed broot binary and assemble the build/ directory
# (binaries + completion scripts + default config + font) ready for release.sh.
#
# This is NOT for normal installation (see https://dystroy.org/broot/install);
# it's the long, multi-toolchain build used to produce official releases.
# Run it from the repository root. It takes no arguments.
#
# To build just one target (e.g. to check a change compiles), use:
#   ./build-target.sh <target>

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_targets.sh"

[[ $# -eq 0 ]] || die "build-all-targets.sh takes no arguments; use ./build-target.sh <target> to build one"

version=$(broot_version)
h1 "Building all targets for $NAME $version   (host $(host_os), darwin=$DARWIN_METHOD)"
[[ $DARWIN_METHOD == skip ]] && warn "the macOS binary will not be built (DARWIN_METHOD=skip)"

# Decide up front whether this build will be staged. Staging needs a clean tree;
# if it's dirty, confirm now rather than after a long build that can't be pushed.
stage_this=no
if staging_configured; then
    if git diff --quiet HEAD 2>/dev/null; then
        stage_this=yes
    else
        warn "working tree has uncommitted changes — this build CANNOT be staged to $BROOT_STAGE_HOST"
        printf '    build locally anyway? it will NOT be staged. [y/N] '
        { read -r reply </dev/tty; } 2>/dev/null || reply=n
        case $reply in
            [yY]|[yY][eE][sS]) ;;
            *) die "aborted — commit your changes, then re-run to stage the build" ;;
        esac
    fi
fi

h2 "Cleaning build/"
rm -rf build && mkdir build
ok "build/ cleaned"

count=0
while IFS= read -r row; do
    [[ -n $row ]] || continue
    build_row "$row"
    count=$((count + 1))
done < <(all_targets)
ok "$count binaries built"

# Copy the completion scripts. They're regenerated by build.rs during every
# compilation, into a build script OUT_DIR under the target dir; grab any one.
h2 "Copying completion scripts"
mkdir -p build/completion
comp_dir=$(find "$CACHE" -type d -path '*/release/build/broot-*/out' 2>/dev/null | sed -n 1p || true)
[[ -n $comp_dir ]] || die "couldn't locate the generated completion scripts under $CACHE/"
cp "$comp_dir"/* build/completion/
ok "completions copied from $comp_dir"

h2 "Copying default configuration"
cp -r resources/default-conf build
ok "done"

h2 "Copying the vscode-icon font"
mkdir -p build/resources
cp resources/icons/vscode/vscode.ttf build/resources
echo "the font file comes from https://github.com/vscode-icons/vscode-icons/ and is licensed as MIT" > build/resources/README.md
ok "done"

printf 'This archive contains pre-compiled binaries.\n\nFor more information, or if you prefer to compile yourself, see https://dystroy.org/broot/install\n' > build/install.md

# Release metadata. Host-independent and deterministic for a given commit (the
# man page date is the commit date), so it's safe for several hosts to stage it
# into the same <id>/.
h2 "Adding release metadata"
echo "This is broot. More info and installation instructions on https://dystroy.org/broot" > build/README.md
cp CHANGELOG.md build/
cp man/page build/broot.1
sed_inplace "s/#version/$version/g" build/broot.1
sed_inplace "s|#date|$(commit_date)|g" build/broot.1
echo "$version" > build/version
ok "metadata added"

# Publish the whole build/ to the staging server (the decision was made up front,
# before the build, so a dirty tree is caught early rather than after all this work).
if [[ $stage_this == yes ]]; then
    h2 "Staging build/ to $BROOT_STAGE_HOST:$BROOT_STAGE_DIR/$(release_id)"
    stage_push build
    ok "staged as $(release_id)"
fi

h1 "FINISHED — build/ is ready for release.sh"
